### ISSUE TITLE
v0.12.1 compilation error: undefined: io.ReadAll

### ISSUE THREAD

**Issue by mattiasgeniar** [ovrclk/akash#1205]
### Issue type

Bug

### What happened

Compilation of the latest version fails.

### How to reproduce it

```
$ git checkout v0.12.1

$ make install
GO111MODULE=on go install -mod=readonly -tags "osusergo,netgo,ledger,static_build" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=akash -X github.com/cosmos/cosmos-sdk/version.AppName=akash -X "github.com/cosmos/cosmos-sdk/version.BuildTags=osusergo,netgo,ledger,static_build" -X github.com/cosmos/cosmos-sdk/version.Version=0.12.1 -X github.com/cosmos/cosmos-sdk/version.Commit=53182423582000bf63fa674245a5008c5b466bf1 -s -w' -trimpath ./cmd/akash
# github.com/ovrclk/akash/provider/gateway/rest
provider/gateway/rest/router.go:155:16: undefined: io.ReadAll
make: *** [make/releasing.mk:20: install] Error 2
```

### Environment

```
$ go version
go version go1.15.5 linux/amd64

$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```

### Anything else we need to know?

Compilation of v0.11 works like a charm on the same machine:

```
$ git checkout v0.11.0-rc1
Previous HEAD position was 5318242 chore(go.mod): bump tendermint to v0.34.9-akash-1
HEAD is now at c0f4453 ci(docker): publish to images ghcr

$ make install
GO111MODULE=on go install -mod=readonly -tags "netgo,ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=akash -X github.com/cosmos/cosmos-sdk/version.AppName=akash -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -X github.com/cosmos/cosmos-sdk/version.Version=0.11.0-rc1 -X github.com/cosmos/cosmos-sdk/version.Commit=c0f44535da90e059bfbc6c5c50758a1681049a18 -s -w' -trimpath ./cmd/akash
```

**Comment by boz** [comment]
go version 1.6 is required now

**Comment by mattiasgeniar** [comment]
My bad: the docs were mentioning golang 1.15 https://docs.akash.network/guides/install

But the README in here mentions golang 1.16.

The compilation works with golang 1.16. 👍
